name: telegram message
on: [pull_request_review, pull_request_review_comment, issue_comment]

jobs:  
  issue_commented:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎉 The job was automatically triggered by a ${{ toJson(github.event) }} event."
