name: telegram message
on: [pull_request_review, pull_request_review_comment, issue_comment, discussion_comment]

jobs:  
  issue_commented:
    runs-on: ubuntu-latest
    steps:
      - name: Issue comment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *${{ github.event.issue_comment.sender.login }} created a issue comment:
            Repository: [${{ github.event.issue_comment.issue.title }}](${{ github.event.issue_comment.issue.html_url }})
            See comment: ${{ github.event.issue_comment.comment.html_url }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event }} event."
