name: telegram message
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  pr_commented:
    if: github.event_name == 'pull_request_review_comment'
    runs-on: ubuntu-latest
    steps:
      - name: PR comment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            **${{ github.event.pull_request_review_comment.sender.login }}** created a pull request comment:
            Repository: [${{ github.event.pull_request_review_comment.pull_request.title }}](${{ github.event.pull_request_review_comment.pull_request.html_url }})
            See comment: ${{ github.event.pull_request_review_comment.comment._links.html.href }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎉 The job was automatically triggered by a ${{ toJson(github.event) }} event."
