name: telegram message
on:
  pull_request:
  pull_request_review:


jobs:
  create_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎉 The job was automatically triggered by a ${{ toJson(github.event) }} event."
