name: telegram message
on:
  pull_request:
    types: [review_requested]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  create_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          debug: true
          message: |
            ${{ github.actor }} created pull request:
            Commit message: ${{ github.event.pull_request.title }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Reviewers: ** ${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }} **
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎉 The job was automatically triggered by a ${{ toJson(github.event) }} event."

  issue_commented:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Issue comment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            ${{ github.event.sender.login }} created a issue comment:
            Repository: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})
            See comment: ${{ github.event.comment.html_url }}
            Author: ${{ github.event.issue.user.login }}

  pr_commented:
    if: github.event_name == 'pull_request_review_comment'
    runs-on: ubuntu-latest
    steps:
      - name: PR comment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            ${{ github.event.sender.login }} created a pull request comment:
            Repository: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            See comment: ${{ github.event.comment.html_url }}
            Author: ${{ github.event.pull_request.user.login }}

  pr_reviewed:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: PR reviewed
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            ${{ github.event.review.user.login }} has approved pull request:
            Repository: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            Author: ${{ github.event.pull_request.user.login }}

